apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: workspace
      mountPath: /workspace
  params:
   - name: service
     type: string
  steps:
    - name: cleanup
      workingDir: /workspace
      image: registry.cn-shanghai.aliyuncs.com/zhonglun/centos7-zhonglun:v1
      script: |
        #!/bin/bash
        rm -rf ./"$(params.service)"

