apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: svn-clone
spec:
  params:
  - name: branch
    type: string
  - name: service
    type: string
  - name: env
    type: string
  results:
    - name: revision
      description: the svn revision of the snv branch
  steps:
    - name: svn-clone
      image: registry-vpc.cn-shanghai.aliyuncs.com/zhonglun/svn-client:1.7
      args:
        - "$(params.branch)"
        - "$(params.service)"
      workingDir: /workspace
      script: |
        #!/bin/bash -x
        branch=$1
        service=$2 
        year=${branch:0:4}
        month=${branch:4:2}
        svnurl=http://svn.cnzhonglunnet.com/svn/zlnet/code/project/branch/${year}/${month}/${branch}/${service}@HEAD 
        svn co $svnurl --username svnadmin   --password Zhonglun@2020
        revision=$(svn info $svnurl --username svnadmin   --password Zhonglun@2020  | awk '/Last Changed Rev/ {print $NF}')
        echo  -n  "v${revision}" > $(results.revision.path)
        pwd
        ls -l
        echo "-------------"
        cat  $(results.revision.path)
        echo "++++++++++++"
        cat  $(results.revision.path)
    - name: maven-build
      image: registry-vpc.cn-shanghai.aliyuncs.com/tektonzl/maven:3-openjdk-8
      workingDir: /workspace/$(params.service)
      script: |
        #!/bin/bash -x
        mvn -f  $(params.service)-pom/pom.xml clean install package -P $(params.env)  -Dmaven.test.skip=true
        echo "*****************************************************"
        ls /scripts -l
        cat /scripts/start.sh
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        for target  in  ` find ./ -name target ` 
        do
           cp   -rL  /scripts   ${target}/
           for script in `ls  ${target}/scripts/`
           do
                chmod a+x  ${target}/scripts/${script}
           done  
        done
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  workspaces:
  - name: workspace
    mountPath: /workspace
    optional: true
  - name: scripts
    mountPath: /scripts
  - name: mavencache
    mountPath: /root/.m2/repository
    optional: true
