apiVersion: v1
data:
  service.webhook.dingding: |-
    url: https://oapi.dingtalk.com/robot/send?access_token=47f094a42fb7942dac60980d10b25ccd9f7d8f9e34db92461774118fd41f2b0d
    headers: #optional headers
    - name: Content-Type
      value: application/json
  template.github-commit-status: |-
    webhook:
     dingding:
       method: POST
       body: |
         {
           "msgtype": "text",
           "text":{"content":"Application {{.app.metadata.name}} sync is {{.app.status.sync.status}} \nhealth is {{.app.status.health.status}}  - yes"}
         }
  trigger.sync-operation-change: |-
    - when:  app.status.health.status == 'Healthy' and app.status.sync.status in  ["Synced"]
      oncePer: app.status.sync.revision
      send: [github-commit-status]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"argocd-notifications-cm","namespace":"argocd"}}
  creationTimestamp: "2022-08-22T09:22:33Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-08-22T09:22:33Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:service.webhook.dingding: {}
        f:template.github-commit-status: {}
        f:trigger.sync-operation-change: {}
    manager: agent
    operation: Update
    time: "2022-08-24T07:01:04Z"
  name: argocd-notifications-cm
  namespace: argocd
  resourceVersion: "19924015"
  uid: b1df132d-b605-4175-be47-a8b228c60501

