---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: evc-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: evc-role-cluster
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources: [deployments]
    verbs: ["*"]

  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [kopf.dev]
    resources: [ephemeralvolumeclaims]
    verbs: ["*"]
    
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: evc-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: evc-role-cluster
subjects:
  - kind: ServiceAccount
    name: evc-account
    namespace: default
