apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: make-web-image
spec:
  resources:
    outputs:
      - name: alireg
        type: image
  params:
  - name: service
    type: string
  - name: revision
    type: string
  steps:
    - image: registry.cn-shanghai.aliyuncs.com/zhonglun/centos7-zhonglun:v1
      name: check-file
      resources: {}
      workingDir: /workspace/$(params.service)/$(params.service)-web/target
      script: |
        #!/bin/bash
        echo "!!!!!!!!!!!!!!!!!!!!!!"
        echo $(params.revision)
        echo "!!!!!!!!!!!!!!!!!!!!!!!"
        cat /config/Dockerfile     
        ls / 
        echo "**************************"
    - args:
      - --dockerfile=/config/Dockerfile
      - --build-arg=JAR=$(params.service)-web-1.0.0-exec.jar
      - --destination=$(resources.outputs.alireg.url)/$(params.service)-web:$(params.revision)
      - --context=.
      workingDir: /workspace/$(params.service)/$(params.service)-web/target
      command:
        - /kaniko/executor
      env:
      - name: DOCKER_CONFIG
        value: /tekton/home/.docker/
      image: registry.cn-shanghai.aliyuncs.com/tektonzl/kaniko-project-executor:v1.3.0-debug
      name: build-and-push
      resources: {}
  workspaces:
    - name: workspace
      mountPath: /workspace
      optional: true
    - name: dockerfile
      mountPath: /config
